name: vibematch
description: "VibeMatch - Matching Video to Audio"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  ffmpeg_kit_flutter: ^6.0.3
  file_picker: ^8.0.5
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  firebase_vertexai: ^0.2.2
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
